package com.diginet.springmvc.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.Gson;
import com.google.gson.annotations.Expose;

/**
 * InstanceVO generated by hbm2java 
 */
@SuppressWarnings("all")
@Entity(name = "InstanceVO")
@Table(name = "tbl_instance", catalog = "diginet")
public class InstanceVO implements java.io.Serializable {

	
	public InstanceVO(Integer id, int instance_type, String instance_name,
			int instance_status, int jvm_initmemory, int jvm_maxmemory,
			int log_file_maxsize, int log_file_maxfiles, int log_file_level,
			String path_export_support_logs, Date summer_time_start,
			Date summer_time_end, String server_ip, int server_port,
			int server_keep_alive_interval, int remote_server_comm_type,
			String remote_server_url, String remote_server_ip,
			Integer remote_server_port, String remote_server_token,
			String remote_server_user, String remote_server_user_passwd,
			String remote_server_certificate, Integer remote_server_id,
			Integer remote_server_keep_alive_interval,
			Integer remote_server_events_interval, String path_import_person,
			String path_import_company, String path_import_pendrive_operations,
			String path_export_files, int concurrent_proc_task,
			int task_saving_days, int event_collect_interval,
			String path_import_events, int concurrent_time_event_files,
			int concurrent_proc_files, int concurrent_numb_event_files,
			int saving_event_days, int deviceLimit) {
		super();
		this.id = id;
		this.instance_type = instance_type;
		this.instance_name = instance_name;
		this.instance_status = instance_status;
		this.jvm_initmemory = jvm_initmemory;
		this.jvm_maxmemory = jvm_maxmemory;
		this.log_file_maxsize = log_file_maxsize;
		this.log_file_maxfiles = log_file_maxfiles;
		this.log_file_level = log_file_level;
		this.path_export_support_logs = path_export_support_logs;
		this.summer_time_start = summer_time_start;
		this.summer_time_end = summer_time_end;
		this.server_ip = server_ip;
		this.server_port = server_port;
		this.server_keep_alive_interval = server_keep_alive_interval;
		this.remote_server_comm_type = remote_server_comm_type;
		this.remote_server_url = remote_server_url;
		this.remote_server_ip = remote_server_ip;
		this.remote_server_port = remote_server_port;
		this.remote_server_token = remote_server_token;
		this.remote_server_user = remote_server_user;
		this.remote_server_user_passwd = remote_server_user_passwd;
		this.remote_server_certificate = remote_server_certificate;
		this.remote_server_id = remote_server_id;
		this.remote_server_keep_alive_interval = remote_server_keep_alive_interval;
		this.remote_server_events_interval = remote_server_events_interval;
		this.path_import_person = path_import_person;
		this.path_import_company = path_import_company;
		this.path_import_pendrive_operations = path_import_pendrive_operations;
		this.path_export_files = path_export_files;
		this.concurrent_proc_task = concurrent_proc_task;
		this.task_saving_days = task_saving_days;
		this.event_collect_interval = event_collect_interval;
		this.path_import_events = path_import_events;
		this.concurrent_time_event_files = concurrent_time_event_files;
		this.concurrent_proc_files = concurrent_proc_files;
		this.concurrent_numb_event_files = concurrent_numb_event_files;
		this.saving_event_days = saving_event_days;
		this.deviceLimit = deviceLimit;
	}
	
	
	@Expose
	@JsonProperty("id")
	private Integer id;

	@Expose
	@JsonProperty("instance_type")
	private int instance_type;

	@Expose
	@JsonProperty("instance_name")
	private String instance_name;

	@Expose
	@JsonProperty("instance_status")
	private int instance_status;

	@Expose
	@JsonProperty("jvm_initmemory")
	private int jvm_initmemory;

	@Expose
	@JsonProperty("jvm_maxmemory")
	private int jvm_maxmemory;

	@Expose
	@JsonProperty("log_file_maxsize")
	private int log_file_maxsize;

	@Expose
	@JsonProperty("log_file_maxfiles")
	private int log_file_maxfiles;

	@Expose
	@JsonProperty("log_file_level")
	private int log_file_level;

	@Expose
	@JsonProperty("path_export_support_logs")
	private String path_export_support_logs;
 
	@Expose
	@JsonProperty("summer_time_start")
	private Date summer_time_start;
 
	@Expose
	@JsonProperty("summer_time_end")  
	private Date summer_time_end;
 
	@Expose
	@JsonProperty("server_ip")
	private String server_ip; 

	@Expose
	@JsonProperty("server_port")
	private int server_port;

	@Expose
	@JsonProperty("server_keep_alive_interval")
	private int server_keep_alive_interval;

	@Expose
	@JsonProperty("remote_server_comm_type")
	private int remote_server_comm_type;

	@Expose
	@JsonProperty("remote_server_url")
	private String remote_server_url;

	@Expose
	@JsonProperty("remote_server_ip")
	private String remote_server_ip;

	@Expose
	@JsonProperty("remote_server_port")
	private Integer remote_server_port;

	@Expose
	@JsonProperty("remote_server_token")
	private String remote_server_token;

	@Expose
	@JsonProperty("remote_server_user")
	private String remote_server_user;

	@Expose
	@JsonProperty("remote_server_user_passwd")
	private String remote_server_user_passwd;

	@Expose
	@JsonProperty("remote_server_certificate")
	private String remote_server_certificate;

	@Expose
	@JsonProperty("remote_server_id")
	private Integer remote_server_id;

	@Expose
	@JsonProperty("remote_server_keep_alive_interval")
	private Integer remote_server_keep_alive_interval;

	@Expose
	@JsonProperty("remote_server_events_interval")
	private Integer remote_server_events_interval;

	@Expose
	@JsonProperty("path_import_person")
	private String path_import_person;

	@Expose
	@JsonProperty("path_import_company")
	private String path_import_company;

	@Expose
	@JsonProperty("path_import_pendrive_operations")
	private String path_import_pendrive_operations;

	@Expose
	@JsonProperty("path_export_files")
	private String path_export_files;

	@Expose
	@JsonProperty("concurrent_proc_task")
	private int concurrent_proc_task;

	@Expose
	@JsonProperty("task_saving_days")
	private int task_saving_days;

	@Expose
	@JsonProperty("event_collect_interval")
	private int event_collect_interval;

	@Expose
	@JsonProperty("path_import_events")
	private String path_import_events;

	@Expose
	@JsonProperty("concurrent_time_event_files")
	private int concurrent_time_event_files;

	@Expose
	@JsonProperty("concurrent_proc_files")
	private int concurrent_proc_files;

	@Expose
	@JsonProperty("concurrent_numb_event_files")
	private int concurrent_numb_event_files;

	@Expose
	@JsonProperty("saving_event_days")
	private int saving_event_days;

	@Expose(serialize = true)
	private String endDate;

	@Expose(serialize = true)
	private int deviceLimit;

	@Expose(serialize = true)
	private String strInstanceType;
	
	@Expose(serialize = true)
	private String strInstanceStatus;

	private transient List<DeviceVO> tbl_devices = new ArrayList<DeviceVO>();

	public InstanceVO() {

	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "instance_type", nullable = false)
	public int getInstanceType() {
		return this.instance_type;
	}

	public void setInstanceType(int instanceType) {
		this.instance_type = instanceType;
	}

	@Column(name = "instance_name", nullable = false, length = 20)
	public String getInstanceName() {
		return this.instance_name;
	}

	public void setInstanceName(String instanceName) {
		this.instance_name = instanceName;
	}

	@Column(name = "instance_status", nullable = false)
	public int getInstanceStatus() {
		return this.instance_status;
	}

	public void setInstanceStatus(int instanceStatus) {
		this.instance_status = instanceStatus;
	}

	@Column(name = "jvm_initmemory", insertable = false, nullable = false)
	public int getJvmInitmemory() {
		return this.jvm_initmemory;
	}

	public void setJvmInitmemory(int jvmInitmemory) {
		this.jvm_initmemory = jvmInitmemory;
	}

	@Column(name = "jvm_maxmemory", insertable = false, nullable = false)
	public int getJvmMaxMemory() {
		return this.jvm_maxmemory;
	}

	public void setJvmMaxMemory(int jvmMaxMemory) {
		this.jvm_maxmemory = jvmMaxMemory;
	}

	@Column(name = "log_file_maxsize", insertable = false, nullable = false)
	public int getLogFileMaxsize() {
		return this.log_file_maxsize;
	}

	public void setLogFileMaxsize(int logFileMaxsize) {
		this.log_file_maxsize = logFileMaxsize;
	}

	@Column(name = "log_file_maxfiles", insertable = false, nullable = false)
	public int getLogFileMaxfiles() {
		return this.log_file_maxfiles;
	}

	public void setLogFileMaxfiles(int logFileMaxfiles) {
		this.log_file_maxfiles = logFileMaxfiles;
	}

	@Column(name = "log_file_level", insertable = false, nullable = false)
	public int getLogFileLevel() {
		return this.log_file_level;
	}

	public void setLogFileLevel(int logFileLevel) {
		this.log_file_level = logFileLevel;
	}

	@Column(name = "path_export_support_logs", insertable = false, nullable = false, length = 100)
	public String getPathExportSupportLogs() {
		return this.path_export_support_logs;
	}

	public void setPathExportSupportLogs(String pathExportSupportLogs) {
		this.path_export_support_logs = pathExportSupportLogs;
	}

	@Column(name = "summer_time_start", length = 10)
	public Date getSummerTimeStart() {
		return this.summer_time_start;
//		if (this.summer_time_end == null) {
//		}
//		DateFormat sdt = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.S");
//		String str = "";
//		Date date = new Date();
//		try {
//			str = new SimpleDateFormat("yyyy-MM-dd").format((Date) sdt.parse(this.summer_time_start.toString()));
//			date = new SimpleDateFormat("yyyy-MM-dd").parse(str);
//		} catch (ParseException e) {
//			e.printStackTrace();
//		}
//		return date;
	}

	public void setSummerTimeStart(Date summerTimeStart) {
		this.summer_time_start = summerTimeStart;
	}

	@Column(name = "summer_time_end", length = 10)
	public Date getSummerTimeEnd() {
//		if (this.summer_time_end == null) {
			return this.summer_time_end;
//		}
//		DateFormat sdt = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.S");
//		String str = "";
//		Date date = new Date();
//		try {
//			str = new SimpleDateFormat("dd/MM/yyyy").format((Date) sdt.parse(this.summer_time_end.toString()));
//			date = new SimpleDateFormat("dd/MM/yyyy").parse(str);
//		} catch (ParseException e) {
//			e.printStackTrace();
//		}
//		return date;
	}

	public void setSummerTimeEnd(Date summerTimeEnd) {
		this.summer_time_end = summerTimeEnd;
	}

	@Column(name = "server_ip", insertable = false, nullable = false, length = 16)
	public String getServerIp() {
		return this.server_ip;
	}

	public void setServerIp(String serverIp) {
		this.server_ip = serverIp;
	}

	@Column(name = "server_port", insertable = false, nullable = false)
	public int getServerPort() {
		return this.server_port;
	}

	public void setServerPort(int serverPort) {
		this.server_port = serverPort;
	}

	@Column(name = "server_keep_alive_interval", insertable = false, nullable = false)
	public int getServerKeepAliveInterval() {
		return this.server_keep_alive_interval;
	}

	public void setServerKeepAliveInterval(int serverKeepAliveInterval) {
		this.server_keep_alive_interval = serverKeepAliveInterval;
	}

	@Column(name = "remote_server_comm_type", insertable = false, nullable = false)
	public int getRemoteServerCommType() {
		return this.remote_server_comm_type;
	}

	public void setRemoteServerCommType(int remoteServerCommType) {
		this.remote_server_comm_type = remoteServerCommType;
	}

	@Column(name = "remote_server_url", length = 200)
	public String getRemoteServerUrl() {
		return this.remote_server_url;
	}

	public void setRemoteServerUrl(String remoteServerUrl) {
		this.remote_server_url = remoteServerUrl;
	}

	@Column(name = "remote_server_ip", length = 16)
	public String getRemoteServerIp() {
		return this.remote_server_ip;
	}

	public void setRemoteServerIp(String remoteServerIp) {
		this.remote_server_ip = remoteServerIp;
	}

	@Column(name = "remote_server_port")
	public Integer getRemoteServerPort() {
		return this.remote_server_port;
	}

	public void setRemoteServerPort(Integer remoteServerPort) {
		this.remote_server_port = remoteServerPort;
	}

	@Column(name = "remote_server_token", length = 200)
	public String getRemoteServerToken() {
		return this.remote_server_token;
	}

	public void setRemoteServerToken(String remoteServerToken) {
		this.remote_server_token = remoteServerToken;
	}

	@Column(name = "remote_server_user", nullable = true, length = 20)
	public String getRemoteServerUser() {
		return this.remote_server_user;
	}

	public void setRemoteServerUser(String remoteServerUser) {
		this.remote_server_user = remoteServerUser;
	}

	@Column(name = "remote_server_user_passwd", nullable = true, length = 40)
	public String getRemoteServerUserPasswd() {
		return this.remote_server_user_passwd;
	}

	public void setRemoteServerUserPasswd(String remoteServerUserPasswd) {
		this.remote_server_user_passwd = remoteServerUserPasswd;
	}

	@Column(name = "remote_server_certificate")
	public String getRemoteServerCertificate() {
		return this.remote_server_certificate;
	}

	public void setRemoteServerCertificate(String remoteServerCertificate) {
		this.remote_server_certificate = remoteServerCertificate;
	}

	@Column(name = "remote_server_id")
	public Integer getRemoteServerId() {
		return this.remote_server_id;
	}

	public void setRemoteServerId(Integer remoteServerId) {
		this.remote_server_id = remoteServerId;
	}

	@Column(name = "remote_server_keep_alive_interval")
	public Integer getRemoteServerKeepAliveInterval() {
		return this.remote_server_keep_alive_interval;
	}

	public void setRemoteServerKeepAliveInterval(Integer remoteServerKeepAliveInterval) {
		this.remote_server_keep_alive_interval = remoteServerKeepAliveInterval;
	}

	@Column(name = "remote_server_events_interval")
	public Integer getRemoteServerEventsInterval() {
		return this.remote_server_events_interval;
	}

	public void setRemoteServerEventsInterval(Integer remoteServerEventsInterval) {
		this.remote_server_events_interval = remoteServerEventsInterval;
	}

	@Column(name = "path_import_person", insertable = false, nullable = false, length = 100)
	public String getPathImportPerson() {
		return this.path_import_person;
	}

	public void setPathImportPerson(String pathImportPerson) {
		this.path_import_person = pathImportPerson;
	}

	@Column(name = "path_import_company", insertable = false, nullable = false, length = 100)
	public String getPathImportCompany() {
		return this.path_import_company;
	}

	public void setPathImportCompany(String pathImportCompany) {
		this.path_import_company = pathImportCompany;
	}

	@Column(name = "path_import_pendrive_operations", insertable = false, nullable = false, length = 100)
	public String getPathImportPendriveOperations() {
		return this.path_import_pendrive_operations;
	}

	public void setPathImportPendriveOperations(String pathImportPendriveOperations) {
		this.path_import_pendrive_operations = pathImportPendriveOperations;
	}

	@Column(name = "path_export_files", insertable = false, nullable = false, length = 100)
	public String getPathExportFiles() {
		return this.path_export_files;
	}

	public void setPathExportFiles(String pathExportFiles) {
		this.path_export_files = pathExportFiles;
	}

	@Column(name = "concurrent_proc_task", insertable = false, nullable = false)
	public int getConcurrentProcTask() {
		return this.concurrent_proc_task;
	}

	public void setConcurrentProcTask(int concurrentProcTask) {
		this.concurrent_proc_task = concurrentProcTask;
	}

	@Column(name = "task_saving_days", insertable = false, nullable = false)
	public int getTaskSavingDays() {
		return this.task_saving_days;
	}

	public void setTaskSavingDays(int taskSavingDays) {
		this.task_saving_days = taskSavingDays;
	}

	@Column(name = "event_collect_interval", insertable = false, nullable = false)
	public int getEventCollectInterval() {
		return this.event_collect_interval;
	}

	public void setEventCollectInterval(int eventCollectInterval) {
		this.event_collect_interval = eventCollectInterval;
	}

	@Column(name = "path_import_events", insertable = false, nullable = false, length = 100)
	public String getPathImportEvents() {
		return this.path_import_events;
	}

	public void setPathImportEvents(String pathImportEvents) {
		this.path_import_events = pathImportEvents;
	}

	@Column(name = "concurrent_time_event_files", insertable = false, nullable = false)
	public int getConcurrentTimeEventFiles() {
		return this.concurrent_time_event_files;
	}

	public void setConcurrentTimeEventFiles(int concurrentTimeEventFiles) {
		this.concurrent_time_event_files = concurrentTimeEventFiles;
	}

	@Column(name = "concurrent_proc_files", insertable = false, nullable = false)
	public int getConcurrentProcFiles() {
		return this.concurrent_proc_files;
	}

	public void setConcurrentProcFiles(int concurrentProcFiles) {
		this.concurrent_proc_files = concurrentProcFiles;
	}

	@Column(name = "concurrent_numb_event_files", insertable = false, nullable = false)
	public int getConcurrentNumbEventFiles() {
		return this.concurrent_numb_event_files;
	}

	public void setConcurrentNumbEventFiles(int concurrentNumbEventFiles) {
		this.concurrent_numb_event_files = concurrentNumbEventFiles;
	}

	@Column(name = "saving_event_days", insertable = false, nullable = false)
	public int getSavingEventDays() {
		return this.saving_event_days;
	}

	public void setSavingEventDays(int savingEventDays) {
		this.saving_event_days = savingEventDays;
	}

	@Transient
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Transient
	public int getDeviceLimit() {
		return deviceLimit;
	}

	public void setDeviceLimit(int deviceLimit) {
		this.deviceLimit = deviceLimit;
	}

	@Transient
	@JsonProperty("strInstanceType")
	public String getStrInstanceType() {
		return strInstanceType;
	}

	public void setStrInstanceType(String strInstanceType) {
		this.strInstanceType = strInstanceType;
	}
	
	@Transient
	@JsonProperty("strInstanceStatus")
	public String getStrInstanceStatus() {
		return strInstanceStatus;
	}

	public void setStrInstanceStatus(String strInstanceStatus) {
		this.strInstanceStatus = strInstanceStatus;
	}
	
	@OneToMany(fetch = FetchType.LAZY)
	public List<DeviceVO> getTblDevices() {
		return this.tbl_devices;
	}
	
	public void setTblDevices(List<DeviceVO> tblDevices) {
		this.tbl_devices = tblDevices;
	}
	
	@Override
	public String toString(){
		return new Gson().toJson(this);
	}
}
